require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'Hirely' do
  config = use_native_modules!
  permissions_path = '../node_modules/react-native-permissions/ios'

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )
  pod 'Permission-LocationAccuracy', :path => "#{permissions_path}/LocationAccuracy"
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse" 
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
  pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app' 
  pod 'RNFBMessaging', :path => '../node_modules/@react-native-firebase/messaging'
  pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'
  pod 'ReactNativeKeyboardManager', :path => '../node_modules/react-native-keyboard-manager'
  pod 'react-native-viewpager', :path => '../node_modules/@react-native-community/viewpager'

  pod 'RNExitApp', :path => '../node_modules/react-native-exit-app'

  target 'HirelyTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
#  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
  end
end
