export const profileListData = [
  {
    id: 0,
    title: 'Edit Profile',
    routeName: 'editProfile',
    bgColor: '#FAEFFF',
    iconColor: '#CB65FF',
    iconName: 'edit',
    iconType: 'antdesign',
    urlParam: '',
  },
  {
    id: 1,
    title: 'My Address',
    routeName: 'myAddress',
    bgColor: '#FEF1F2',
    iconColor: '#FA7A7C',
    iconName: 'address-card',
    iconType: 'font-awesome-5',
    urlParam: '',
  },
  {
    id: 2,
    title: 'Help',
    routeName: 'help',
    bgColor: '#E8FAF4',
    iconColor: '#0C80C4',
    iconName: 'help',
    iconType: 'ionicon',
    urlParam: '',
  },
  {
    id: 3,
    title: 'Notifications',
    bgColor: '#E8FAF4',
    iconColor: '#20D1A1',
    iconName: 'notifications',
    iconType: 'ionicon',
    urlParam: '',
  },
  {
    id: 4,
    title: 'Referrals',
    bgColor: '#FFF8D5',
    iconColor: '#FFDC2C',
    iconName: 'groups',
    iconType: 'materialicons',
    urlParam: '',
  },
  {
    id: 5,
    title: 'About Us',
    bgColor: '#EEF9FE',
    iconColor: '#5BC8FA',
    routeName: 'cmsContent',
    iconName: 'info-with-circle',
    iconType: 'entypo',
    urlParam: 'about',
  },
  {
    id: 6,
    title: 'Terms & Conditions',
    routeName: 'cmsContent',
    bgColor: '#FEF1F2',
    iconColor: '#FA7A7C',
    iconName: 'info-with-circle',
    iconType: 'entypo',
    urlParam: 'terms',
  },
  {
    id: 7,
    title: 'Privacy Policy',
    routeName: 'cmsContent',
    bgColor: '#EFF0FE',
    iconColor: '#5A6FFA',
    iconName: 'info-with-circle',
    iconType: 'entypo',
    urlParam: 'privacy',
  },
  {
    id: 8,
    title: 'FAQs',
    routeName: 'cmsContent',
    bgColor: '#F1FAEA',
    iconColor: '#72CE30',
    iconName: 'info-with-circle',
    iconType: 'entypo',
    urlParam: 'faq',
  },
];

export const guestListData = [
  {
    id: 0,
    title: 'About Us',
    bgColor: '#EEF9FE',
    iconColor: '#5BC8FA',
    routeName: 'cmsContent',
    iconName: 'info-with-circle',
    iconType: 'entypo',
    urlParam: 'about',
  },
  {
    id: 1,
    title: 'Terms & Conditions',
    routeName: 'cmsContent',
    bgColor: '#FEF1F2',
    iconColor: '#FA7A7C',
    iconName: 'info-with-circle',
    iconType: 'entypo',
    urlParam: 'terms',
  },
  {
    id: 2,
    title: 'Privacy Policy',
    routeName: 'cmsContent',
    bgColor: '#EFF0FE',
    iconColor: '#5A6FFA',
    iconName: 'info-with-circle',
    iconType: 'entypo',
    urlParam: 'privacy',
  },
  {
    id: 3,
    title: 'FAQs',
    routeName: 'cmsContent',
    bgColor: '#F1FAEA',
    iconColor: '#72CE30',
    iconName: 'info-with-circle',
    iconType: 'entypo',
    urlParam: 'faq',
  },
];
